task_id:"g_C-nCPwxLa1kXcBaVdfs" check_item:{check_item_id:"JA02znXI4lPr80HfS9vb4" command:{command_id:"adYMcOLbdjGXN1uOXnnP_" command_line:"progate diagnose"}} check_item:{check_item_id:"KeLCE2v-6yb0CaRDkTe05" command:{command_id:"qoWkWR_6Hep2aCRjlGmic" command_line:"bash ./tools/git_init_completed.sh"}} check_item:{check_item_id:"jzOzt4hTwJ-zCxswzBmqQ" command:{command_id:"mDwDg35p6aax_dkYg72fJ" command_line:"npm run lint:check"} command:{command_id:"Bqy843TtaVAYj4sISiZoQ" command_line:"npm run format:check"}} check_item:{check_item_id:"6qlgdYEfJ-zQIX_1AcVaM" command:{command_id:"74qKSyCE1r03MWyHMG571" command_line:"npm run test:redirect"} command:{command_id:"IlhulNk6PYd_6u7URWGdN" command_line:"npm run test:dialog_message"}} check_item:{check_item_id:"DSZAlu4Fzge-QltwvIa9-" command:{command_id:"SQCOiB0wGfUPUJwgeugWA" command_line:"npm run test"}}