task_id:"_z2u45qMAiAoBj8qo5uDH" check_item:{check_item_id:"51mfY0_Qk83UJ5e6EVYFx" command:{command_id:"JqRDStVcfc01hbPHRmY-w" command_line:"progate diagnose"}} check_item:{check_item_id:"gb1R1dtrQQX2CesQt6Ysr" command:{command_id:"mlfH9jWRQQQ2fbkEW_BOY" command_line:"npm run test"}} check_item:{check_item_id:"JniMDtrohqLQ494hwoMRd" command:{command_id:"yLDtSf3XpOeK-kurNJpdh" command_line:"bash ./tools/git_init_completed.sh"}} check_item:{check_item_id:"vAUXnYtGtnGSi6UsBDqkx" command:{command_id:"YJE9cUYmCCccV8N8qQldY" command_line:"npm run lint:check"} command:{command_id:"R5gnuamrYfTAeCBSfeGbH" command_line:"npm run format:check"}}